server: 
  port: 9998

spring:
  application:
    name: vocabulary-lesson

  datasource:
    url: jdbc:mysql://mysql:3306/vocabulary_lesson?createDatabaseIfNotExist=true
    username: root
    password: mapyeugau110418
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG